-- =========================================================
-- 도장판 (Weekly Stamp Tracker) Supabase 셋업 SQL
-- 이 파일 전체를 복사해서 Supabase SQL Editor에 붙여넣고 RUN 하세요!
-- =========================================================

-- 기존 테이블 완전 삭제
DROP TABLE IF EXISTS custom_events CASCADE;
DROP TABLE IF EXISTS study_stamps CASCADE;
DROP TABLE IF EXISTS daily_targets CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- 1. profiles
CREATE TABLE profiles (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    password TEXT NOT NULL DEFAULT '0000',
    is_password_set BOOLEAN DEFAULT false,
    role TEXT NOT NULL DEFAULT 'child'
);

INSERT INTO profiles (id, name, password, is_password_set, role) VALUES 
('yoonseo', '윤서', '0000', false, 'child'),
('yeonwoo', '연우', '0000', false, 'child'),
('yeontaek', '연택', '0000', false, 'child'),
('admin', '관리자', '1234', false, 'admin');

-- 2. daily_targets
CREATE TABLE daily_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES profiles(id) ON DELETE CASCADE,
    date_str TEXT NOT NULL,
    target_count INTEGER DEFAULT 0,
    UNIQUE(user_id, date_str)
);

-- 3. study_stamps
CREATE TABLE study_stamps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES profiles(id) ON DELETE CASCADE,
    date_str TEXT NOT NULL,
    stamp_index INTEGER NOT NULL,
    UNIQUE(user_id, date_str, stamp_index)
);

-- 4. custom_events (용돈 지급 기록)
CREATE TABLE custom_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES profiles(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    amount INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 권한 설정 (anon 누구나 읽고 쓰기 가능)
-- ==========================================
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_targets ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_stamps ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public_access" ON profiles FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "public_access" ON daily_targets FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "public_access" ON study_stamps FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "public_access" ON custom_events FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
