-- =========================================================
-- 우리가족 공부 기록장 (Study Tracker) Supabase 셋업 SQL
-- =========================================================
-- 이 코드를 복사해서 Supabase 대시보드의 'SQL Editor' 탭에 붙여넣고 RUN(실행) 버튼을 누르시면 됩니다.

-- 1. profiles 테이블 생성
CREATE TABLE profiles (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    grade TEXT NOT NULL,
    school_code TEXT NOT NULL,
    money INTEGER DEFAULT 0,
    coupons INTEGER DEFAULT 0,
    accumulated_extra_minutes INTEGER DEFAULT 0,
    last_study_date TEXT DEFAULT '',
    today_studied_minutes INTEGER DEFAULT 0,
    target_weekday INTEGER DEFAULT 120,
    target_weekend INTEGER DEFAULT 60,
    target_vacation INTEGER DEFAULT 120
);

-- 초기 프로필 데이터 삽입
INSERT INTO profiles (id, name, grade, school_code) VALUES 
('yoonseo', '윤서', '고2', '7531379'),
('yeonwoo', '연우', '중1', '7751044'),
('yeontaek', '연택', '초4', '7751123');

-- 2. transactions (내역) 테이블 생성
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    date_str TEXT NOT NULL,
    title TEXT NOT NULL,
    amount INTEGER DEFAULT 0,
    coupons INTEGER DEFAULT 0,
    is_deduct BOOLEAN DEFAULT false
);

-- 3. todos (학습 계획표) 테이블 생성
CREATE TABLE todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    date_str TEXT NOT NULL,
    task_text TEXT NOT NULL,
    is_completed BOOLEAN DEFAULT false
);

-- 4. custom_events (사용자 지정 달력 일정) 테이블 생성
CREATE TABLE custom_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES profiles(id) ON DELETE CASCADE, -- null이면 전체 공통 일정
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    date_str TEXT NOT NULL, -- YYYYMMDD
    event_text TEXT NOT NULL
);

-- =========================================================
-- (선택 사항) Row Level Security (RLS) 정책 임시 해제
-- 본 프로젝트는 가족용이므로 빠른 테스트를 위해 모든 접근을 허용합니다.
-- =========================================================
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE todos DISABLE ROW LEVEL SECURITY;
ALTER TABLE custom_events DISABLE ROW LEVEL SECURITY;
