-- =========================================================
-- 도장판 (Weekly Stamp Tracker) Supabase 셋업 SQL
-- =========================================================

-- 기존 테이블이 있다면 깨끗하게 지우고 새로 시작합니다. (주의: 기존 데이터는 모두 삭제됩니다)
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS todos CASCADE;
DROP TABLE IF EXISTS custom_events CASCADE;
DROP TABLE IF EXISTS study_stamps CASCADE;
DROP TABLE IF EXISTS daily_targets CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- 1. profiles 테이블 생성
CREATE TABLE profiles (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    password TEXT NOT NULL DEFAULT '0000',
    is_password_set BOOLEAN DEFAULT false,
    role TEXT NOT NULL DEFAULT 'child'
);

-- 초기 프로필 데이터 삽입
INSERT INTO profiles (id, name, password, is_password_set, role) VALUES 
('yoonseo', '윤서', '0000', false, 'child'),
('yeonwoo', '연우', '0000', false, 'child'),
('yeontaek', '연택', '0000', false, 'child'),
('admin', '관리자', '1234', false, 'admin');

-- 2. daily_targets (날짜별 목표 도장 개수)
CREATE TABLE daily_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES profiles(id) ON DELETE CASCADE,
    date_str TEXT NOT NULL, -- YYYY-MM-DD
    target_count INTEGER DEFAULT 0,
    UNIQUE(user_id, date_str)
);

-- 3. study_stamps (찍은 도장 기록)
CREATE TABLE study_stamps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES profiles(id) ON DELETE CASCADE,
    date_str TEXT NOT NULL, -- YYYY-MM-DD
    stamp_index INTEGER NOT NULL, -- 0~9 (1시간 단위, 최대 10칸)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, date_str, stamp_index)
);

-- RLS 해제 (빠른 테스트용)
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE daily_targets DISABLE ROW LEVEL SECURITY;
ALTER TABLE study_stamps DISABLE ROW LEVEL SECURITY;
