-- =========================================================
--  도장판 PostgreSQL 스키마
--
--  ⚠ 반드시 stamp 데이터베이스에 연결한 상태에서 실행하세요.
--     학원앱(annest) DB 에 실행하면 안 됩니다.
--     확인:  \conninfo   →  database "stamp" 라고 나와야 합니다.
--
--  실행:  sudo -u postgres psql -d stamp -f 01_schema.sql
-- =========================================================

\echo '현재 연결된 DB:'
SELECT current_database();

-- 실수로 다른 DB 에 실행하는 것을 막습니다
DO $$
BEGIN
  IF current_database() <> 'stamp' THEN
    RAISE EXCEPTION '이 스크립트는 stamp 데이터베이스에서만 실행할 수 있습니다 (현재: %)', current_database();
  END IF;
END $$;

-- 1. 사용자
CREATE TABLE IF NOT EXISTS profiles (
  id              TEXT PRIMARY KEY,
  name            TEXT    NOT NULL,
  password        TEXT    NOT NULL DEFAULT '0000',
  is_password_set BOOLEAN NOT NULL DEFAULT false,
  role            TEXT    NOT NULL DEFAULT 'child'
);

-- 2. 하루 목표 시간
CREATE TABLE IF NOT EXISTS daily_targets (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      TEXT    NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  date_str     TEXT    NOT NULL,
  target_count INTEGER NOT NULL DEFAULT 0,
  UNIQUE (user_id, date_str)
);

-- 3. 도장
CREATE TABLE IF NOT EXISTS study_stamps (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        TEXT    NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  date_str       TEXT    NOT NULL,
  stamp_index    INTEGER NOT NULL,
  is_coupon_used BOOLEAN NOT NULL DEFAULT false,
  UNIQUE (user_id, date_str, stamp_index)
);

CREATE INDEX IF NOT EXISTS idx_stamp_date ON study_stamps (date_str);

-- 4. 용돈/쿠폰 지급 기록
--    settled_until = 이 지급이 "며칠분까지" 정산한 것인지
CREATE TABLE IF NOT EXISTS custom_events (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       TEXT    NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  event_type    TEXT    NOT NULL,
  amount        INTEGER NOT NULL DEFAULT 0,
  coupon_amount INTEGER NOT NULL DEFAULT 0,
  settled_until TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_event_user ON custom_events (user_id, event_type);

-- 5. 로그인 세션 (한 번 로그인하면 계속 유지되도록)
CREATE TABLE IF NOT EXISTS sessions (
  token      TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_session_user ON sessions (user_id);

-- ---------------------------------------------------------
-- 권한: stamp 롤만 접근할 수 있게
-- ---------------------------------------------------------
GRANT USAGE ON SCHEMA public TO stamp;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO stamp;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO stamp;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO stamp;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO stamp;

\echo '스키마 생성 완료'
