-- =========================================================
--  아이 미기록 Web Push 구독 및 중복 발송 방지 테이블
--  실행: sudo -u postgres psql -v ON_ERROR_STOP=1 -d stamp -f 04_push_notifications.sql
-- =========================================================

DO $$
BEGIN
  IF current_database() <> 'stamp' THEN
    RAISE EXCEPTION '이 스크립트는 stamp 데이터베이스에서만 실행할 수 있습니다 (현재: %)', current_database();
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    TEXT        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  endpoint   TEXT        NOT NULL UNIQUE,
  p256dh     TEXT        NOT NULL,
  auth       TEXT        NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_push_subscription_user
  ON push_subscriptions (user_id);

CREATE TABLE IF NOT EXISTS push_delivery_log (
  user_id       TEXT        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  date_str      TEXT        NOT NULL,
  reminder_hour INTEGER     NOT NULL DEFAULT 13,
  sent_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  success_count INTEGER     NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, date_str, reminder_hour),
  CHECK (reminder_hour BETWEEN 0 AND 23)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON push_subscriptions, push_delivery_log TO stamp;
GRANT USAGE, SELECT ON SEQUENCE push_subscriptions_id_seq TO stamp;

\echo '푸시 알림 테이블 생성 완료'
